"""Rename home/away to white/black

Revision ID: 45b54b1bd981
Revises: f1a196e768d7
Create Date: 2025-06-23 22:07:02.614788

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45b54b1bd981'
down_revision = 'f1a196e768d7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('white_team_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('black_team_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('white_score', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('black_score', sa.Float(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'teams', ['white_team_id'], ['id'])
        batch_op.create_foreign_key(None, 'teams', ['black_team_id'], ['id'])
        batch_op.drop_column('away_team_id')
        batch_op.drop_column('home_team_id')
        batch_op.drop_column('home_score')
        batch_op.drop_column('away_score')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('away_score', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('home_score', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('home_team_id', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('away_team_id', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'teams', ['home_team_id'], ['id'])
        batch_op.create_foreign_key(None, 'teams', ['away_team_id'], ['id'])
        batch_op.drop_column('black_score')
        batch_op.drop_column('white_score')
        batch_op.drop_column('black_team_id')
        batch_op.drop_column('white_team_id')

    # ### end Alembic commands ###