"""add match.status, set tournament.total_rounds default

Revision ID: 8ab47d9e8cd9
Revises: c6bd6e3f961f
Create Date: 2025-06-22 23:09:16.638698

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ab47d9e8cd9'
down_revision = 'c6bd6e3f961f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###