"""describe your change

Revision ID: c6bd6e3f961f
Revises: ecdc627878ba
Create Date: 2025-06-22 23:06:44.525981

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6bd6e3f961f'
down_revision = 'ecdc627878ba'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###