"""Fix all schema issues

Revision ID: f1a196e768d7
Revises: 8ab47d9e8cd9
Create Date: 2025-06-23 18:31:45.549526

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1a196e768d7'
down_revision = '8ab47d9e8cd9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###